// tags.ts
const possibleTags = [
    "Difficult to Read",
    "High Complexity",
    "Duplicated",
    "Variable with non-significant name",    
    "for loop having its iteration variable overwritten",
    "Boolean comparison attempted with while loop",
    "while condition tested again inside its block",
    "Non utilization of elif/else statement",
    "Redundant or unnecessary loop",
    "Arbitrary number of for loop executions instead of while",
    "Function accessing variables from outer scope",
    "Functions/variables with non-significant name",
    "Statement with no effect",
    "Consecutive equal if statements with distinct operations in their blocks",
    "elif/else retesting already checked conditions",
    "Redundant or unnecessary use of lists",
    "Redefinition of built-in",
    "Specific verification for instances of open test cases",
    "Arbitrary organization of declarations",
    "Redundant operations inside loop",
    "Checking all possible combinations unnecessarily",
    "Too many declarations in a single line of code",
    "Variable assigned to itself",
    "Variables with arbitrary values (Magic Numbers) used in operations",
    "Arbitrary manipulations to modify declared variables",
    "Consecutive distinct if statements with the same operations in their blocks",
    "Unnecessary elif/else",
    "Arithmetic expression instead of Boolean",
    "Repeated commands inside if-elif-else blocks",
    "Inconsistent return declaration",
    "Arbitrary treatment of the stopping point of reading values",
    "Boolean validation variable instead of elif/else",
    "Arbitrary internal treatment of loop boundaries",
    "Multiple distinct loops that operates over the same iterable",
    "Verification for non explicit conditions",
    "Redundant typecast",
    "Functions not documented in the Docstring format",
    "Unused variable",
    "Variable unnecessarily initialized",
    "Redundant or simplifiable Boolean comparison",
    "Too many return declarations inside a function",
    "Nested if statements instead of Boolean comparison",
    "Exaggerated use of variables to assign expressions",
    "Use of intermediary variable to loop control",
    "Redundant or unnecessary return declaration",
    "Unnecessary or redundant semicolon",
    "Boolean comparison separated in intermediary variables",
    "Long line commentary",
    "Unused import"
  ];
  
  export default possibleTags;
  