export interface User {
    _id?: string; // Optional since it will be generated by MongoDB
    username: string;
    email: string;
    imageURL?: string;
    password: string;
    isVerified: boolean;
    isAdmin: boolean;
    forgotPasswordToken?: string;
    forgotPasswordTokenExpiry?: Date;
    verifyToken?: string;
    verifyTokenExpiry?: Date;
  }
  